### PR TITLE
Corrected example in comment for World.step with interpolation

### PR DESCRIPTION
**Pull request by TomWHall**

### CODE REVIEW

**Comment by schteppe** [comment]
Just ran this code in [a jsfiddle](https://jsfiddle.net/1Lsf9rt1/) and I got a negative value for `deltaTime` in the first frame... Most of the times the value is positive though.
I'm not sure how this could happen, since `performance.now()` is run before `requestAnimationFrame`?

**Comment by TomWHall** [comment]
Hmmm, I'm not sure either. The Mozilla docs state that t is "the current time when callbacks queued by requestAnimationFrame begin to fire", which I thought must be after the startTime assignment. Perhaps it's safest to forget the startTime and allow the very first iteration to do a 0 size step? I.e. [like this](https://jsfiddle.net/1Lsf9rt1/4/)? Would that cause a problem?

**Comment by schteppe** [comment]
Using timeSinceLastCalled=0 for the first step would make the world take one fixed step forward, no matter if using variable timesteps or fixed. I think avoiding the first zero-step would be good. Maybe `if(deltaTime){ world.step(...) }`?

**Comment by TomWHall** [comment]
Sorry for the delay. I hadn't realized that was the world step behaviour with a 0 time step. You're right, although it would be nice to achieve a way where that loop doesn't need to do any checks like this every time (even like my || check) - but maybe the overhead is negligible?

**Comment by schteppe** [comment]
Checking once per frame is totally negligible. I'm more concerned about the learning part, as this is an important example code snippet for beginners.

What do you think about this? https://github.com/schteppe/p2.js/commit/5b6b2efd74b30591e1a7d8f6eac4a587da0cbd60

**Comment by TomWHall** [comment]
Yeah, that looks good to me. Should there be "var" for the timeSeconds and deltaTime local variables?

**Comment by schteppe** [comment]
Correct! Thanks.

**Pull request closed without merging**
