### PR TITLE
To repair the new body, its sleepstate status is sleepy

### PR DESCRIPTION
**Pull request by joneszhuchinagd**
To repair the new body, its sleepstate status is sleepy .
Body.js have modified somewhere.

### CODE REVIEW

**Comment by schteppe** [comment]
I guess this solves it, but why not just do ```this.idleTime=0;``` in the ```Body``` constructor?

**Comment by joneszhuchinagd** [comment]
You are right, I hope you can improve in the latest version.I just let you aware of the problem。

**Comment by joneszhuchinagd** [comment]
I have thought of your solution, but I'm afraid influence to the robustness of the code

**Comment by joneszhuchinagd** [comment]
You know, the p2 is going to hot up in China, because of the introduction of the physics engine egret game framework.I made a table tennis game with p2, and found a lot of collision detection is not accurate.If too fast, it will affect the judgment of collision detection.So I made some before the collision detection.

**Comment by schteppe** [comment]
"influence to the robustness of the code"? How? Did you test it? I will push the constructor fix in a minute.

Regarding the inaccurate collision detection: The best solution for that is Continuous Collision Detection (CCD), but it's unfortunately not available in p2 yet. I have some ideas on how to implement it though. What you can do for now is make the time step smaller.

Very happy to hear about the Egret engine! Cool :D

**Comment by schteppe** [comment]
See https://github.com/schteppe/p2.js/commit/02ecb382868861374006b81d1027bb2380066088

**Comment by joneszhuchinagd** [comment]
nice~

**Pull request closed without merging**
